WITH BSS AS(
SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES 
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY BOOK_ID)
    
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(T.SALES * B.PRICE) AS TOTAL_SALES
    FROM BOOK B
    JOIN BSS T ON B.BOOK_ID = T.BOOK_ID
    JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
    GROUP BY A.AUTHOR_ID, B.CATEGORY
    ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;