WITH ED AS (
SELECT ID, PARENT_ID
    FROM ECOLI_DATA),
    
PID AS (SELECT PARENT_ID, COUNT(PARENT_ID) AS CHILD_COUNT
    FROM ED
    GROUP BY PARENT_ID)
    
SELECT E.ID, CASE
                WHEN P.CHILD_COUNT IS NULL THEN 0
                ELSE P.CHILD_COUNT
                END AS CHILD_COUNT
    FROM ED E
    LEFT JOIN PID P ON E.ID = P.PARENT_ID
    ORDER BY E.ID ASC;