WITH ONLINE AS(
    SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
        FROM ONLINE_SALE
        WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
),

OFFLINE AS (
    SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
        FROM OFFLINE_SALE 
        WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'),

UNITED_TABLE AS (
    SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
        FROM ONLINE
    UNION
    SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT 
        FROM OFFLINE)

SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM UNITED_TABLE
    ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;