SELECT C.CAR_ID,
       C.CAR_TYPE,
       ROUND(
           C.DAILY_FEE * 30 * 
           NVL(1 - (CAST(REPLACE(P.DISCOUNT_RATE, '%', '') AS NUMBER(5,2)) / 100), 1)
       , 0) AS FEE
  FROM CAR_RENTAL_COMPANY_CAR C
  LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
         ON C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = '30일 이상'
WHERE C.CAR_TYPE IN ('세단', 'SUV')
  -- 2022년 11월에 해당 차량이 대여된 이력이 없어야 함
  AND NOT EXISTS (
      SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
       WHERE H.CAR_ID = C.CAR_ID
         AND H.START_DATE <= TO_DATE('2022-11-30', 'YYYY-MM-DD')
         AND H.END_DATE >= TO_DATE('2022-11-01', 'YYYY-MM-DD')
  )
  -- 30일 대여 기준 요금이 조건에 부합해야 함
  AND ROUND(
           C.DAILY_FEE * 30 * 
           NVL(1 - (CAST(REPLACE(P.DISCOUNT_RATE, '%', '') AS NUMBER(5,2)) / 100), 1)
       , 0) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;

    
    