WITH OUTS AS (
    SELECT ANIMAL_ID
        FROM ANIMAL_OUTS
        WHERE SEX_UPON_OUTCOME NOT LIKE 'Intact%')

SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
    FROM ANIMAL_INS I
    JOIN OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
    WHERE I.SEX_UPON_INTAKE LIKE 'Intact%'
    ORDER BY I.ANIMAL_ID;
