WITH A AS (
SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
    FROM REST_REVIEW 
    GROUP BY REST_ID)
    
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, A.SCORE
    FROM REST_INFO I
    JOIN A ON A.REST_ID = I.REST_ID
    WHERE I.ADDRESS LIKE '서울%'
    ORDER BY A.SCORE DESC, I.FAVORITES DESC;