SELECT TO_NUMBER(TO_CHAR(S.SALES_DATE,'YYYY')) AS YEAR, 
        TO_NUMBER(TO_CHAR(S.SALES_DATE, 'FMMM')) AS MONTH,
        I.GENDER,
        COUNT(DISTINCT I.USER_ID) AS USERS
    FROM USER_INFO I
    JOIN ONLINE_SALE S ON I.USER_ID = S.USER_ID
    WHERE I.GENDER IS NOT NULL
    GROUP BY TO_NUMBER(TO_CHAR(S.SALES_DATE,'YYYY')), TO_NUMBER(TO_CHAR(S.SALES_DATE, 'FMMM')), I.GENDER
    ORDER BY 1 ASC, 2 ASC, 3 ASC;