SELECT COUNT(F.ID) AS FISH_COUNT, N.FISH_NAME AS FISH_NAME
    FROM FISH_NAME_INFO N
    JOIN FISH_INFO F ON F.FISH_TYPE = N.FISH_TYPE
    GROUP BY N.FISH_TYPE, N.FISH_NAME
    ORDER BY FISH_COUNT DESC;