SELECT 
  TO_CHAR(S.SALES_DATE, 'YYYY') AS YEAR,
  TO_CHAR(S.SALES_DATE, 'FMMM') AS MONTH,
  COUNT(DISTINCT I.USER_ID) AS PURCHASED_USERS,
  ROUND(
    COUNT(DISTINCT I.USER_ID) * 1.0 / 
    (SELECT COUNT(*) FROM USER_INFO WHERE TO_CHAR(JOINED, 'YYYY') = '2021'),
    1
  ) AS PURCHASED_RATIO
FROM USER_INFO I
JOIN ONLINE_SALE S ON I.USER_ID = S.USER_ID
WHERE TO_CHAR(I.JOINED,'YYYY') = '2021'
GROUP BY TO_CHAR(S.SALES_DATE, 'YYYY'), TO_CHAR(S.SALES_DATE, 'FMMM')
ORDER BY YEAR ASC, TO_NUMBER(MONTH);
