-- 연월별로 2021년에 가입한 회원 중 상품을 구매한 회원수
SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH,
        COUNT(DISTINCT I.USER_ID) AS PURCHASED_USERS,
        ROUND(COUNT(DISTINCT I.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = '2021'), 1) AS PUCHASED_RATIO
    FROM USER_INFO I
    JOIN ONLINE_SALE S ON I.USER_ID = S.USER_ID
    WHERE YEAR(I.JOINED) = '2021'
    GROUP BY YEAR, MONTH
    ORDER BY YEAR ASC, MONTH ASC;











-- 계산