WITH O AS (
            SELECT ANIMAL_ID
                FROM ANIMAL_OUTS)
                
SELECT NAME, DATETIME
    FROM ANIMAL_INS I
    WHERE I.ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM O)
    ORDER BY I.DATETIME ASC
    LIMIT 3;