WITH AVGO AS (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT -- 총매출 개산용 AMOUNT
                FROM FOOD_ORDER
                WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
                GROUP BY PRODUCT_ID)

SELECT DISTINCT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE * A.AMOUNT AS TOTAL_SALES -- 식품별 총매출
        FROM FOOD_PRODUCT P
        JOIN AVGO A ON  P.PRODUCT_ID = A.PRODUCT_ID
        ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC;

