WITH BORROWDATE AS ( -- 트럭의 대여 기록 + 대여 일수 + 일일 요금
    SELECT 
        H.HISTORY_ID, 
        DATEDIFF(END_DATE, START_DATE) + 1 AS BD, -- 1일 추가!
        C.DAILY_FEE 
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
),
DC AS ( -- 트럭의 기간별 할인율 (소수로 변환)
    SELECT 
        DURATION_TYPE, 
        CAST(REPLACE(DISCOUNT_RATE, '%', '') AS DECIMAL(5,2)) / 100 AS DISCOUNT_RATE -- 고침
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE CAR_TYPE = '트럭'
)
SELECT 
    HISTORY_ID, 
    ROUND(
        CASE
            WHEN BD >= 90 THEN (1 - (SELECT DISCOUNT_RATE FROM DC WHERE DURATION_TYPE = '90일 이상')) * DAILY_FEE * BD -- 일수 곱하기!
            WHEN BD >= 30 THEN (1 - (SELECT DISCOUNT_RATE FROM DC WHERE DURATION_TYPE = '30일 이상')) * DAILY_FEE * BD
            WHEN BD >= 7 THEN (1 - (SELECT DISCOUNT_RATE FROM DC WHERE DURATION_TYPE = '7일 이상')) * DAILY_FEE * BD
            ELSE DAILY_FEE * BD -- 할인 없음: 일일 요금 * 일수
        END
    , 0) AS FEE
FROM BORROWDATE
ORDER BY FEE DESC, HISTORY_ID DESC;
