WITH HOUR_DTS AS(
    SELECT HOUR(DATETIME) AS HOUR_DT
    FROM ANIMAL_OUTS)

SELECT HOUR_DT AS HOUR, COUNT(HOUR_DT) AS COUNT
    FROM HOUR_DTS 
    GROUP BY HOUR_DT
    HAVING HOUR >= 09 AND HOUR < 20
    ORDER BY HOUR_DT ASC;