SELECT P.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE,'YYYY-MM-DD') AS REVIEW_DATE
     FROM MEMBER_PROFILE P
     JOIN REST_REVIEW R ON P.MEMBER_ID = R.MEMBER_ID
     WHERE R.MEMBER_ID = (SELECT MEMBER_ID 
                            FROM REST_REVIEW 
                            GROUP BY MEMBER_ID 
                            ORDER BY COUNT(*) DESC 
                            FETCH FIRST 1 ROW ONLY)
     ORDER BY REVIEW_DATE ASC, R.REVIEW_TEXT ASC;
     
     