WITH P AS (
            SELECT ID AS PID, GENOTYPE AS PGT
                FROM ECOLI_DATA )
                
SELECT E.ID, E.GENOTYPE, P.PGT AS PARENT_GENOTYPE
    FROM ECOLI_DATA E
    JOIN P ON E.PARENT_ID = P.PID
    WHERE E.GENOTYPE & P.PGT = P.PGT
    ORDER BY E.ID;
    