SELECT MCDP_CD AS '진료과코드', COUNT(MCDP_CD) AS '5월예약건수'
    FROM APPOINTMENT 
    WHERE  '2022-05-01' <= APNT_YMD AND '2022-06-01' > APNT_YMD
    GROUP BY MCDP_CD
    ORDER BY 5월예약건수 ASC, 진료과코드 ASC;
   