SELECT SUBSTRING(PRODUCT_CODE, 1, 2) AS CATEGORY, COUNT(PRODUCT_CODE) AS COUNT
    FROM PRODUCT
    GROUP BY SUBSTRING(PRODUCT_CODE, 1, 2) -- PRODUCT_CODE의 앞에서부터 두글자
    ORDER BY SUBSTRING(PRODUCT_CODE, 1, 2)