SELECT B.TITLE, B.BOARD_ID, U.REPLY_ID, U.WRITER_ID, U.CONTENTS, 
        DATE_FORMAT(U.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
    FROM USED_GOODS_BOARD B
    JOIN USED_GOODS_REPLY U ON B.BOARD_ID = U.BOARD_ID
    WHERE B.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
    ORDER BY U.CREATED_DATE ASC, B.TITLE ASC;
    