WITH A AS( SELECT DEPT_ID, ROUND(AVG(SAL),0) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
)

SELECT D.DEPT_ID, D.DEPT_NAME_EN, A.AVG_SAL
    FROM HR_DEPARTMENT D
    JOIN A ON D.DEPT_ID = A.DEPT_ID
    ORDER BY A.AVG_SAL DESC;
    
 