WITH T AS( 
    SELECT BOOK_ID, SUM(SALES) AS TOTAL
        FROM BOOK_SALES 
        WHERE DATE_FORMAT(SALES_DATE,'%Y-%m-%d') BETWEEN '2022-01-01' AND '2022-01-31'
        GROUP BY BOOK_ID
)

SELECT B.CATEGORY, SUM(T.TOTAL) AS TOTAL_SALES
    FROM BOOK B
    JOIN T ON B.BOOK_ID = T.BOOK_ID
    GROUP BY B.CATEGORY
    ORDER BY CATEGORY ASC;
