WITH MAXS AS (
SELECT CATEGORY, MAX(PRICE) AS MP
    FROM FOOD_PRODUCT 
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY)
    
SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME
    FROM FOOD_PRODUCT F
    JOIN MAXS M ON F.CATEGORY = M.CATEGORY AND F.PRICE = M.MP
    ORDER BY F.PRICE DESC;