WITH MAXP AS(
SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT 
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY)
    
SELECT F.CATEGORY, M.MAX_PRICE, F.PRODUCT_NAME
    FROM FOOD_PRODUCT F
    JOIN MAXP M ON F.CATEGORY = M.CATEGORY 
                    AND F.PRICE = M.MAX_PRICE   
    ORDER BY M.MAX_PRICE DESC;
    